{{config(
	schema = "DATA_PIPELINE",
	materialized = "table"
)}}
WITH select_step1 as (
  SELECT
    "AGENT_DEMOGRAPHICS_MQT"."PKG_ID" AS "PKG_ID",
    "AGENT_DEMOGRAPHICS_MQT"."FROM_PKG_ID" AS "FROM_PKG_ID",
    "AGENT_DEMOGRAPHICS_MQT"."MRD_TYPE_CD" AS "MRD_TYPE_CD",
    "AGENT_DEMOGRAPHICS_MQT"."BILLING_METHOD" AS "BILLING_METHOD",
    "AGENT_DEMOGRAPHICS_MQT"."AGN_KEY" AS "AGN_KEY",
    "AGENT_DEMOGRAPHICS_MQT"."ACTIVATION_SOURCE" AS "ACTIVATION_SOURCE",
    "AGENT_DEMOGRAPHICS_MQT"."VENDOR" AS "VENDOR",
    "AGENT_DEMOGRAPHICS_MQT"."STATUS" AS "STATUS",
    "AGENT_DEMOGRAPHICS_MQT"."SITE" AS "SITE"
  FROM
    "DATA_PIPELINE"."AGENT_DEMOGRAPHICS_MQT"
)
SELECT
  *
FROM
  select_step1
LIMIT
  100