{{config(
	schema = "DATA_PIPELINE",
	materialized = "table"
)}}
WITH select_step1 as (
  SELECT
    "CANCEL_REASONS_MQT"."REASONCODETYPE" AS "REASONCODETYPE",
    "CANCEL_REASONS_MQT"."REASONNAME" AS "REASONNAME",
    "CANCEL_REASONS_MQT"."REASON_CODE_GROUP" AS "REASON_CODE_GROUP",
    "CANCEL_REASONS_MQT"."REASONNAMEROLLUP" AS "REASONNAMEROLLUP",
    "CANCEL_REASONS_MQT"."PLAN_ID" AS "PLAN_ID",
    "CANCEL_REASONS_MQT"."# OF PLANS" AS "# OF PLANS"
  FROM
    "DATA_PIPELINE"."CANCEL_REASONS_MQT"
)
SELECT
  *
FROM
  select_step1
LIMIT
  100