{{config(
	schema = "DATA_PIPELINE",
	materialized = "view"
)}}
WITH select_step1 as (
  SELECT
    "FACT_SUBSCRIPTION_ACTIVITY"."SBSCRN_ID" AS "SBSCRN_ID",
    "FACT_SUBSCRIPTION_ACTIVITY"."ACTVTY_TYPE_ID" AS "ACTVTY_TYPE_ID",
    "FACT_SUBSCRIPTION_ACTIVITY"."ACTVTY_DT" AS "ACTVTY_DT",
    "FACT_SUBSCRIPTION_ACTIVITY"."ACTVTY_TS" AS "ACTVTY_TS",
    "FACT_SUBSCRIPTION_ACTIVITY"."PARNT_ACCT_NUM" AS "PARNT_ACCT_NUM",
    "FACT_SUBSCRIPTION_ACTIVITY"."VEH_KEY" AS "VEH_KEY",
    "FACT_SUBSCRIPTION_ACTIVITY"."DVC_KEY" AS "DVC_KEY",
    "FACT_SUBSCRIPTION_ACTIVITY"."DVC_ID" AS "DVC_ID",
    "FACT_SUBSCRIPTION_ACTIVITY"."EQMNT_KEY" AS "EQMNT_KEY",
    "FACT_SUBSCRIPTION_ACTIVITY"."EQMNT_ID" AS "EQMNT_ID",
    "FACT_SUBSCRIPTION_ACTIVITY"."PLAN_KEY" AS "PLAN_KEY",
    "FACT_SUBSCRIPTION_ACTIVITY"."PLAN_ID" AS "PLAN_ID",
    "FACT_SUBSCRIPTION_ACTIVITY"."FROM_PLAN_KEY" AS "FROM_PLAN_KEY",
    "FACT_SUBSCRIPTION_ACTIVITY"."FROM_PLAN_ID" AS "FROM_PLAN_ID",
    "FACT_SUBSCRIPTION_ACTIVITY"."PROD_KEY" AS "PROD_KEY",
    "FACT_SUBSCRIPTION_ACTIVITY"."PROD_ID" AS "PROD_ID",
    "FACT_SUBSCRIPTION_ACTIVITY"."PKG_ID" AS "PKG_ID",
    "FACT_SUBSCRIPTION_ACTIVITY"."AGN_KEY" AS "AGN_KEY",
    "FACT_SUBSCRIPTION_ACTIVITY"."DEACTIVATION_REASON_CODE" AS "DEACTIVATION_REASON_CODE",
    "FACT_SUBSCRIPTION_ACTIVITY"."BILLING_METHOD" AS "BILLING_METHOD",
    "FACT_SUBSCRIPTION_ACTIVITY"."CALL_REASON" AS "CALL_REASON",
    "FACT_SUBSCRIPTION_ACTIVITY"."CALL_DISPOSITION" AS "CALL_DISPOSITION"
  FROM
    "SCHEMA_INFO"."FACT_SUBSCRIPTION_ACTIVITY"
)
SELECT
  *
FROM
  select_step1
LIMIT
  100