{{config(
  schema = "DATA_PIPELINE",
  materialized = "view"
)}}
WITH OFFERS_AND_PACKAGES as (
  SELECT
    "PLAN_ID" AS "PLAN_ID",
    "PACKAGE" AS "PACKAGE",
    "LEN" AS "LEN",
    "ROLLUP1" AS "ROLLUP1",
    "STARTDATE" AS "STARTDATE",
    "ENDDATE" AS "ENDDATE",
    "PLAN_KEY" AS "PLAN_KEY",
    "FROM_PLAN_KEY" AS "FROM_PLAN_KEY",
    "FROM_PLAN_ID" AS "FROM_PLAN_ID",
    "BILLING_METHOD" AS "BILLING_METHOD",
    "REVENUE" AS "REVENUE",
    "PLAN_NAME" AS "PLAN_NAME"
  FROM
    {{ ref('OFFERS_AND_PACKAGES_MQT_DBT') }}
),
CANCEL_REASONS as (
  select
    "REASONCODETYPE" AS "REASONCODETYPE",
    "REASONNAME" AS "REASONNAME",
    "REASON_CODE_GROUP" AS "REASON_CODE_GROUP",
    "REASONNAMEROLLUP" AS "REASONNAMEROLLUP",
    "PLAN_ID" AS "PLAN_ID1",
    "# OF PLANS" AS "# OF PLANS"
  from 
     {{ ref('CANCEL_REASONS_MQT_DBT') }} 
),
join_step2 as (
  SELECT
    OFFERS_AND_PACKAGES.*,
    CANCEL_REASONS.*,
    case when {{ dbt_utils.datediff("STARTDATE", "ENDDATE", 'day') }} < 0 then 9999 
    else {{ dbt_utils.datediff("STARTDATE", "ENDDATE", 'day') }}
    end as SUB_DURATION
  FROM
    OFFERS_AND_PACKAGES
    LEFT OUTER JOIN CANCEL_REASONS ON (
      OFFERS_AND_PACKAGES."PLAN_ID" = CANCEL_REASONS."PLAN_ID1"
    )
  WHERE STARTDATE BETWEEN '2015-01-01' and '2018-12-31'
)
  SELECT
    *,
    {{ dbt_utils.width_bucket("REVENUE", 1, 30, 10) }} as REVENUE_BUCKET
  FROM
    join_step2 limit 100