{{config(
	schema = "DATA_PIPELINE_PUBLISH",
	materialized = "view"
)}}
WITH select_step1 as (
  SELECT
    "MASTER_PLAN_TABLE_WDATES"."PLAN_ID" AS "PLAN_ID",
    "MASTER_PLAN_TABLE_WDATES"."PLAN_NAME" AS "PLAN_NAME",
    "MASTER_PLAN_TABLE_WDATES"."MER" AS "MER",
    "MASTER_PLAN_TABLE_WDATES"."DISC" AS "DISC",
    "MASTER_PLAN_TABLE_WDATES"."PACKAGE" AS "PACKAGE",
    "MASTER_PLAN_TABLE_WDATES"."LEN" AS "LEN",
    "MASTER_PLAN_TABLE_WDATES"."ROLLUP1" AS "ROLLUP1",
    "MASTER_PLAN_TABLE_WDATES"."STARTDATE" AS "STARTDATE",
    "MASTER_PLAN_TABLE_WDATES"."ENDDATE" AS "ENDDATE"
  FROM
    "SCHEMA_INFO"."MASTER_PLAN_TABLE_WDATES"
),
join_step2 as (
  SELECT
    select_step1."PLAN_ID" AS "PLAN_ID",
    select_step1."PLAN_NAME" AS "PLAN_NAME",
    select_step1."MER" AS "REVENUE",
    select_step1."DISC" AS "DISC",
    select_step1."PACKAGE" AS "PACKAGE",
    select_step1."LEN" AS "LEN",
    select_step1."ROLLUP1" AS "ROLLUP1",
    select_step1."STARTDATE" AS "STARTDATE",
    select_step1."ENDDATE" AS "ENDDATE",
    "FACT_SUBSCRIPTION_ACTIVITY"."SBSCRN_ID" AS "SBSCRN_ID",
    "FACT_SUBSCRIPTION_ACTIVITY"."PLAN_KEY" AS "PLAN_KEY",
    "FACT_SUBSCRIPTION_ACTIVITY"."PLAN_ID" AS "PLAN_ID1",
    "FACT_SUBSCRIPTION_ACTIVITY"."FROM_PLAN_KEY" AS "FROM_PLAN_KEY",
    "FACT_SUBSCRIPTION_ACTIVITY"."FROM_PLAN_ID" AS "FROM_PLAN_ID",
    "FACT_SUBSCRIPTION_ACTIVITY"."FROM_OFR_ID" AS "FROM_OFR_ID",
    "FACT_SUBSCRIPTION_ACTIVITY"."PROD_KEY" AS "PROD_KEY",
    "FACT_SUBSCRIPTION_ACTIVITY"."PROD_ID" AS "PROD_ID",
    "FACT_SUBSCRIPTION_ACTIVITY"."FROM_PROD_KEY" AS "FROM_PROD_KEY",
    "FACT_SUBSCRIPTION_ACTIVITY"."FROM_PROD_ID" AS "FROM_PROD_ID",
    "FACT_SUBSCRIPTION_ACTIVITY"."PKG_ID" AS "PKG_ID",
    "FACT_SUBSCRIPTION_ACTIVITY"."FROM_PKG_ID" AS "FROM_PKG_ID",
    "FACT_SUBSCRIPTION_ACTIVITY"."AGN_KEY" AS "AGN_KEY",
    "FACT_SUBSCRIPTION_ACTIVITY"."DEACTIVATION_REASON_CODE" AS "DEACTIVATION_REASON_CODE",
    "FACT_SUBSCRIPTION_ACTIVITY"."BILLING_METHOD" AS "BILLING_METHOD",
    "FACT_SUBSCRIPTION_ACTIVITY"."CALL_REASON" AS "CALL_REASON",
    "FACT_SUBSCRIPTION_ACTIVITY"."CALL_DISPOSITION" AS "CALL_DISPOSITION"
  FROM
    select_step1
    LEFT OUTER JOIN "SCHEMA_INFO"."FACT_SUBSCRIPTION_ACTIVITY" ON (
      select_step1."PLAN_ID" = "FACT_SUBSCRIPTION_ACTIVITY"."PLAN_ID"
    )
),
group_by_step3 as (
  SELECT
    CAST(join_step2."BILLING_METHOD" as varchar) AS "BILLING_METHOD",
    CAST(join_step2."DEACTIVATION_REASON_CODE" as varchar) AS "DEACTIVATION_REASON_CODE",
    CAST(join_step2."CALL_REASON" as INT) AS "CALL_REASON",
    CAST(join_step2."PACKAGE" as varchar) AS "PACKAGE",
    CAST(join_step2."STARTDATE" as varchar) AS "STARTDATE",
    CAST(join_step2."ENDDATE" as varchar) AS "ENDDATE",
    CAST(join_step2."PLAN_ID" as INT) AS "PLAN_ID",
    CAST(join_step2."LEN" as varchar) AS "TERM",
    CAST(join_step2."PLAN_NAME" as varchar) AS "PLAN_NAME",
    CAST(join_step2."ROLLUP1" as varchar) AS "ROLLUP1",
    CAST(join_step2."AGN_KEY" as INT) AS "AGN_KEY",
    CAST(join_step2."SBSCRN_ID" as INT) AS "SBSCRN_ID",
    CAST(Sum("REVENUE") as varchar) AS "REVENUE"
  FROM
    join_step2
  GROUP BY
    join_step2."BILLING_METHOD",
    join_step2."DEACTIVATION_REASON_CODE",
    join_step2."CALL_REASON",
    join_step2."PACKAGE",
    join_step2."STARTDATE",
    join_step2."ENDDATE",
    join_step2."PLAN_ID",
    join_step2."LEN",
    join_step2."PLAN_NAME",
    join_step2."ROLLUP1",
    join_step2."AGN_KEY",
    join_step2."SBSCRN_ID"
),
filter_step4 as (
  SELECT
    *
  FROM
    group_by_step3
  WHERE
    (
      group_by_step3."REVENUE" > 0
      AND group_by_step3."REVENUE" IS NOT NULL
    )
)
SELECT
  *
FROM
  filter_step4
LIMIT
  100