{{config(
	schema = "DATA_PIPELINE",
	materialized = "table"
)}}
WITH select_step1 as (
  SELECT
    "OFFERS_AND_PACKAGES_MQT"."PLAN_ID" AS "PLAN_ID",
    "OFFERS_AND_PACKAGES_MQT"."PACKAGE" AS "PACKAGE",
    "OFFERS_AND_PACKAGES_MQT"."LEN" AS "LEN",
    "OFFERS_AND_PACKAGES_MQT"."ROLLUP1" AS "ROLLUP1",
    "OFFERS_AND_PACKAGES_MQT"."STARTDATE" AS "STARTDATE",
    "OFFERS_AND_PACKAGES_MQT"."ENDDATE" AS "ENDDATE",
    "OFFERS_AND_PACKAGES_MQT"."PLAN_KEY" AS "PLAN_KEY",
    "OFFERS_AND_PACKAGES_MQT"."PLAN_ID1" AS "PLAN_ID1",
    "OFFERS_AND_PACKAGES_MQT"."FROM_PLAN_KEY" AS "FROM_PLAN_KEY",
    "OFFERS_AND_PACKAGES_MQT"."FROM_PLAN_ID" AS "FROM_PLAN_ID",
    "OFFERS_AND_PACKAGES_MQT"."BILLING_METHOD" AS "BILLING_METHOD",
    "OFFERS_AND_PACKAGES_MQT"."AGN_KEY" AS "AGN_KEY",
    "OFFERS_AND_PACKAGES_MQT"."REVENUE" AS "REVENUE",
    "OFFERS_AND_PACKAGES_MQT"."PLAN_NAME" AS "PLAN_NAME"
  FROM
    "DATA_PIPELINE"."OFFERS_AND_PACKAGES_MQT"
)
SELECT
  *
FROM
  select_step1
LIMIT
  100